### ISSUE TITLE
SRC images no found correctly

### ISSUE THREAD

**Issue by anton-team** [ajvillegas/image-gallery-metabox#1]
I am being presented with the cases where the images are not attracting me the URL of it.

![capture](https://user-images.githubusercontent.com/30220259/35335540-43584d90-00ec-11e8-914a-03d8ff866daa.PNG)

In some cases, the src attribute is not bringing me the url.

Website Issues: https://www.gosouthside.do/destino/playa-quemaito-barahona-republica-dominicana/

**Comment by ajvillegas** [comment]
Hi @antonagency,

May I ask how you are retrieving your images? It might not be an issue with the plugin, but rather with the function retrieving the data for the front-end. Could you please post the function used?

Also, just in case you are using the `wp_prepare_attachment_for_js` method described in the documentation, please keep in mind that custom image sizes added through `add_image_size` won't work right away with it. For that you must add the custom image size using the `image_size_names_choose` filter. I updated the documentation with an example to illustrate this.

However I understand this might not necessarily be the case with your website. Please post the function used and I'll see if we can figure this one out.

**Comment by anton-team** [comment]
This is the function, it is the same as the documentation.

` <?php
        $i=0;
        foreach( $images as $image ) {
            
            $i++;    
		    
            // Get attachment details
            
            $attachment = wp_prepare_attachment_for_js( $image );

            if($i==1)
                {
                   echo '<div class="item active"> ';   
                }else
                {
                    echo '<div class="item"> '; 
                };?>
		    
                
                    <img src="<?php echo $attachment['sizes']['large']['url']; ?>" alt="<?php echo $attachment['alt']; ?>" />
                </div> 
       <?php }; ?>`

**Comment by anton-team** [comment]
Okay. I understand, thank you very much for the help, I have achieved it.

**Comment by ajvillegas** [comment]
The only thing I can think of is that maybe the `large` size was not generated by WordPress and as a result, the URL comes back as empty when using `wp_prepare_attachment_for_js`. I've noticed that if an uploaded image can't be cropped to a WordPress image size (because of dimension restrictions), then the attachment size won't be generated.

To verify, first obtain the attachment ID for the specific image that's giving you problems (this can be found in the media admin page URL), then `print_r` the `$sizes = $attachment['sizes'];` to see if the `large` size exists within the array.

```php
<?php

// Get attachment details ($attachment_id = attachment ID or object)
$attachment = wp_prepare_attachment_for_js( $attachment_id );

// An sub-array containing details for each size
$sizes = $attachment['sizes'];

// Display array on page
echo '<pre>';
    print_r( $sizes );
echo '</pre>';
``` 
If this is the case, then simply re-upload an image with larger dimension so WordPress can generate the appropriate attachment size.

Hope this helps.

**Comment by ajvillegas** [comment]
I just saw your earlier reply. Glad you got it fixed!
